[package]
name = "ksef-client"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
clap = { version = "4.3", features = ["derive"] }
rcgen = "0.9"
openssl = "0.10"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
rand = "0.8"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
mockito = "0.31"

[[bin]]
name = "certgen"
path = "bin/certgen.rs"
